### PR TITLE
change unnecessary heap allocs to stack allocs

### PR DESCRIPTION
**Pull request by rweichler**
should help with overhead.

### CODE REVIEW

**Comment by ephemer** [comment]
@rweichler can you explain what difference this makes? I'm interested in reducing processing overhead as much as possible but coming from the scripting side of things I'm not as up to speed with memory management as I'd like to be.

**Comment by rweichler** [comment]
Sure. The basic idea is that in most modern operating systems, there's 2 places to allocate memory. On the stack and on the heap. Stack is temporary stuff and heap is more permanent stuff.

The stack basically works like this:
```c
int x;
if(true) {
    int y;
    if(true) {
        int z;
    }
}
some_function(x);
```

So what the OS does is this:
```
<nothing>
x
x, y
x, y, z
x, y
x
x, some_function, x
x
<nothing>
```

Since all of that static scoping stuff can be figured out by the compiler it ends up being way more efficient since you're just pushing and popping stuff from a stack.

On the contrary, with malloc and the like (like all of the Objective-C objects), theres no way for the compiler to tell when the stuff will go away, so it ends up putting the stuff in this heap, which is pretty much a huge chunk of memory with random parts being used and not used. A lot of the time there's fragmentation and stuff which ends up slowing stuff down since it's not all contiguous (kind of like how you have to defrag Windows every once in a while)

**Comment by bartolsthoorn** [comment]
Thank you for this and sorry for the late reply, I was travelling in Canada
for a while. I expect to merge this one tomorrow when I am back home again.

**Comment by ephemer** [comment]
@rweichler thanks for the awesome explanation, that makes sense in terms of the function call stack in JavaScript, for example. Awesome stuff

**Comment by ephemer** [comment]
@rweichler @bartolsthoorn Just implemented this commit for a filterbank we made in NVDSP and got about a 15% reduction in CPU usage. Great stuff.

**Pull request merged**
